name = "MyPkg"
uuid = "c3592960-7982-434f-af5a-fd79500c10e1"
authors = ["Daniel Runge <runge@wias-berlin.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
